// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notification.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notification.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260821083844_AddCallbacks")]
    partial class AddCallbacks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notification.Domain.Callbacks.CallbackAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("EventId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("ux_callback_attempts_event_no");

                    b.ToTable("callback_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_callback_attempts_error", "(result = 'success' AND error_code IS NULL) OR (result <> 'success' AND error_code IS NOT NULL)");

                            t.HasCheckConstraint("ck_callback_attempts_no", "attempt_no BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_callback_attempts_result", "result IN ('success','transient_failure','permanent_failure')");

                            t.HasCheckConstraint("ck_callback_attempts_time", "finished_at >= started_at");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Callbacks.StatusEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("failure_code");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<byte[]>("PayloadEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("payload_encrypted");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("public_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_status_events_public_id");

                    b.HasIndex("TenantId");

                    b.HasIndex("NotificationId", "EventType")
                        .IsUnique()
                        .HasDatabaseName("ux_status_events_notification_type");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_status_events_status_due");

                    b.ToTable("status_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_status_events_attempt_count", "attempt_count BETWEEN 0 AND 6");

                            t.HasCheckConstraint("ck_status_events_status", "status IN ('pending','sending','delivered','failed','cancelled')");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CallbackConfiguredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("callback_configured_at");

                    b.Property<byte[]>("CallbackSecretEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("callback_secret_encrypted");

                    b.Property<string>("CallbackUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("callback_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DisabledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disabled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedLegacyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_legacy_name");

                    b.Property<Guid>("OwnerAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_admin_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAdminId");

                    b.HasIndex("TenantId", "NormalizedLegacyName")
                        .IsUnique()
                        .HasDatabaseName("ux_devices_tenant_legacy_name")
                        .HasFilter("normalized_legacy_name IS NOT NULL");

                    b.HasIndex("TenantId", "OwnerAdminId", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_devices_tenant_owner_created");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_devices_tenant_status_created");

                    b.ToTable("devices", null, t =>
                        {
                            t.HasCheckConstraint("ck_devices_callback", "(callback_url IS NULL AND callback_secret_encrypted IS NULL AND callback_configured_at IS NULL) OR (callback_url IS NOT NULL AND callback_secret_encrypted IS NOT NULL AND callback_configured_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_devices_disabled", "(status = 'active' AND disabled_at IS NULL) OR (status = 'disabled' AND disabled_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_devices_role", "role IN ('source','both')");

                            t.HasCheckConstraint("ck_devices_status", "status IN ('active','disabled')");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Identity.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_admins_email_active")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("TenantId", "Email")
                        .HasDatabaseName("ix_admins_tenant_email");

                    b.ToTable("admins", null, t =>
                        {
                            t.HasCheckConstraint("ck_admins_role", "role IN ('owner')");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Identity.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_admin_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("character varying(19)")
                        .HasColumnName("key_prefix");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("ProducerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("producer_name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_api_keys_hash");

                    b.HasIndex("KeyPrefix")
                        .IsUnique()
                        .HasDatabaseName("ux_api_keys_prefix");

                    b.HasIndex("TenantId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_api_keys_tenant_created");

                    b.HasIndex("TenantId", "DeviceId")
                        .HasDatabaseName("ix_api_keys_tenant_device");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_api_keys_tenant_status");

                    b.HasIndex("DeviceId", "Status", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_api_keys_device_status_created");

                    b.ToTable("api_keys", null, t =>
                        {
                            t.HasCheckConstraint("ck_api_keys_revocation", "(status = 'active' AND revoked_at IS NULL) OR (status = 'revoked' AND revoked_at IS NOT NULL AND revoked_at >= created_at)");

                            t.HasCheckConstraint("ck_api_keys_status", "status IN ('active','revoked')");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at_active")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("ReplacedById");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("AdminId", "FamilyId")
                        .HasDatabaseName("ix_refresh_tokens_admin_family");

                    b.ToTable("refresh_tokens", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_tokens_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_refresh_tokens_revocation", "revoked_at IS NULL OR revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Identity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_slug_active")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Notification.Domain.Notifications.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("provider_message_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("result");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("NotificationId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("ux_delivery_attempts_notification_no");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_delivery_attempts_tenant_created");

                    b.HasIndex("TenantId", "NotificationId")
                        .HasDatabaseName("ix_delivery_attempts_tenant_notification");

                    b.ToTable("delivery_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_delivery_attempts_no", "attempt_no >= 1");

                            t.HasCheckConstraint("ck_delivery_attempts_outcome", "(result = 'success' AND error_code IS NULL) OR (result <> 'success' AND error_code IS NOT NULL)");

                            t.HasCheckConstraint("ck_delivery_attempts_result", "result IN ('success','transient_failure','permanent_failure')");

                            t.HasCheckConstraint("ck_delivery_attempts_time", "finished_at >= started_at");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Notifications.OutboundNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<byte[]>("BodyEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body_encrypted");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("recipient_email");

                    b.Property<string>("RecipientRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("recipient_ref");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<byte[]>("SubjectEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("subject_encrypted");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_notifications_status_next_attempt");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_tenant_created");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_notifications_tenant_status");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasCheckConstraint("ck_notifications_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_notifications_ciphertext", "octet_length(subject_encrypted) > 0 AND octet_length(body_encrypted) > 0");

                            t.HasCheckConstraint("ck_notifications_status", "status IN ('accepted','sending','sent','failed','cancelled')");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Senders.Sender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("from_email");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_name");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("host");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<byte[]>("PasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_encrypted");

                    b.Property<int>("Port")
                        .HasColumnType("integer")
                        .HasColumnName("port");

                    b.Property<bool>("Secure")
                        .HasColumnType("boolean")
                        .HasColumnName("secure");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("username");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ux_senders_tenant_default")
                        .HasFilter("is_default = true AND status = 'active'");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_senders_tenant_key");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_senders_tenant_status");

                    b.ToTable("senders", null, t =>
                        {
                            t.HasCheckConstraint("ck_senders_channel", "channel = 'email'");

                            t.HasCheckConstraint("ck_senders_disabled_default", "status <> 'disabled' OR is_default = false");

                            t.HasCheckConstraint("ck_senders_port", "port BETWEEN 1 AND 65535");

                            t.HasCheckConstraint("ck_senders_status", "status IN ('active','disabled')");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Templates.ContentTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variables");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_templates_tenant_key");

                    b.HasIndex("TenantId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_templates_tenant_status_created");

                    b.ToTable("templates", null, t =>
                        {
                            t.HasCheckConstraint("ck_templates_body_length", "char_length(body) BETWEEN 1 AND 100000");

                            t.HasCheckConstraint("ck_templates_status", "status IN ('draft','active','retired')");

                            t.HasCheckConstraint("ck_templates_variables_array", "jsonb_typeof(variables) = 'array'");
                        });
                });

            modelBuilder.Entity("Notification.Domain.Callbacks.CallbackAttempt", b =>
                {
                    b.HasOne("Notification.Domain.Callbacks.StatusEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Notification.Domain.Callbacks.StatusEvent", b =>
                {
                    b.HasOne("Notification.Domain.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Notifications.OutboundNotification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Notification");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Notification.Domain.Devices.Device", b =>
                {
                    b.HasOne("Notification.Domain.Identity.Admin", "OwnerAdmin")
                        .WithMany()
                        .HasForeignKey("OwnerAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerAdmin");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Notification.Domain.Identity.Admin", b =>
                {
                    b.HasOne("Notification.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Notification.Domain.Identity.ApiKey", b =>
                {
                    b.HasOne("Notification.Domain.Identity.Admin", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Devices.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Device");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Notification.Domain.Identity.RefreshToken", b =>
                {
                    b.HasOne("Notification.Domain.Identity.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Identity.RefreshToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Notification.Domain.Notifications.DeliveryAttempt", b =>
                {
                    b.HasOne("Notification.Domain.Notifications.OutboundNotification", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Senders.Sender", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("Sender");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Notification.Domain.Notifications.OutboundNotification", b =>
                {
                    b.HasOne("Notification.Domain.Identity.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Senders.Sender", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Notification.Domain.Templates.ContentTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Notification.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("Sender");

                    b.Navigation("Template");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Notification.Domain.Senders.Sender", b =>
                {
                    b.HasOne("Notification.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Notification.Domain.Templates.ContentTemplate", b =>
                {
                    b.HasOne("Notification.Domain.Identity.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });
#pragma warning restore 612, 618
        }
    }
}
