using System.Security.Claims;
using System.Text.Json;
using FluentValidation;
using Notification.Api.Contracts.Templates;
using Notification.Application.Templates;
namespace Notification.Api.Endpoints.Templates;

public static class TemplateEndpoints
{
    public static IEndpointRouteBuilder MapTemplateEndpoints(this IEndpointRouteBuilder e) { e.MapPost("/v1/templates", Create).RequireAuthorization("Admin").RequireRateLimiting("template-mutation"); e.MapGet("/v1/templates", List).RequireAuthorization("Admin"); e.MapGet("/v1/templates/{key}", Get).RequireAuthorization("Admin"); e.MapPatch("/v1/templates/{key}", Patch).RequireAuthorization("Admin").RequireRateLimiting("template-mutation"); return e; }
    static bool Tenant(ClaimsPrincipal p, out Guid id) => Guid.TryParse(p.FindFirstValue("tenant_id"), out id);
    static IResult Error(TemplateOperationException x) => x.Code switch { "NOT_FOUND" => Results.NotFound(new { error = "Not found", code = x.Code, statusCode = 404 }), "TEMPLATE_KEY_EXISTS" or "TEMPLATE_INVALID_STATE" => Results.Conflict(new { error = "Template conflict", code = x.Code, statusCode = 409 }), _ => Results.BadRequest(new { error = "Template validation failed", code = x.Code, statusCode = 400, names = x.Names }) };
    static async Task<IResult> Create(CreateTemplateRequest r, IValidator<CreateTemplateRequest> v, TemplateHandlers h, ClaimsPrincipal p, CancellationToken c) { var vr = await v.ValidateAsync(r, c); if (!vr.IsValid) return Results.BadRequest(new { error = "Validation failed", code = "VALIDATION_FAILED", statusCode = 400 }); if (!Tenant(p, out var t)) return Results.Unauthorized(); try { var x = await h.CreateAsync(t, new(r.Key, r.Subject, r.Body, r.Variables), c); return Results.Created($"/v1/templates/{x.Key}", x); } catch (TemplateOperationException x) { return Error(x); } }
    static async Task<IResult> List(string? status, int? limit, string? cursor, TemplateHandlers h, ClaimsPrincipal p, CancellationToken c) { if (!Tenant(p, out var t)) return Results.Unauthorized(); var take = limit ?? 50; if (take is < 1 or > 100 || status is not null and not ("draft" or "active" or "retired")) return Error(new("VALIDATION_FAILED")); try { var x = await h.ListAsync(t, status, take, cursor, c); return Results.Ok(new { items = x.Items, nextCursor = x.NextCursor }); } catch (TemplateOperationException x) { return Error(x); } }
    static async Task<IResult> Get(string key, TemplateHandlers h, ClaimsPrincipal p, CancellationToken c) { if (!Tenant(p, out var t)) return Results.Unauthorized(); try { return Results.Ok(await h.GetAsync(t, key, c)); } catch (TemplateOperationException x) { return Error(x); } }
    static async Task<IResult> Patch(string key, JsonElement body, IValidator<PatchTemplateRequest> v, TemplateHandlers h, ClaimsPrincipal p, CancellationToken c) { if (!Tenant(p, out var t)) return Results.Unauthorized(); if (body.ValueKind != JsonValueKind.Object || !body.EnumerateObject().Any()) return Error(new("VALIDATION_FAILED")); var allowed = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "subject", "body", "variables", "status" }; if (body.EnumerateObject().Any(x => !allowed.Contains(x.Name) || x.Value.ValueKind == JsonValueKind.Null)) return Error(new("VALIDATION_FAILED")); PatchTemplateRequest? r; try { r = body.Deserialize<PatchTemplateRequest>(new JsonSerializerOptions { PropertyNameCaseInsensitive = true }); } catch { return Error(new("VALIDATION_FAILED")); } if (r is null || !(await v.ValidateAsync(r, c)).IsValid) return Error(new("VALIDATION_FAILED")); try { return Results.Ok(await h.UpdateAsync(t, key, new(r.Subject, r.Body, r.Variables, r.Status), c)); } catch (TemplateOperationException x) { return Error(x); } }
}
