using System.Security.Claims;
using System.Text.Json;
using FluentValidation;
using Notification.Api.Contracts.Templates;
using Notification.Application.Templates;
using Notification.Domain.Templates;
namespace Notification.Api.Endpoints.Templates;

public static class TemplateEndpoints
{
    public static IEndpointRouteBuilder MapTemplateEndpoints(this IEndpointRouteBuilder e)
    {
        e.MapPost("/v1/templates", Create).RequireAuthorization("Admin").RequireRateLimiting("template-mutation"); e.MapGet("/v1/templates", List).RequireAuthorization("Admin"); e.MapGet("/v1/templates/{identifier}", Get).RequireAuthorization("Admin"); e.MapPatch("/v1/templates/{identifier}", Patch).RequireAuthorization("Admin").RequireRateLimiting("template-mutation"); e.MapPost("/v1/templates/{id:guid}/versions", Clone).RequireAuthorization("Admin").RequireRateLimiting("template-mutation"); e.MapPost("/v1/templates/{id:guid}/publish", Publish).RequireAuthorization("Admin").RequireRateLimiting("template-mutation"); e.MapPost("/v1/templates/{id:guid}/retire", Retire).RequireAuthorization("Admin").RequireRateLimiting("template-mutation"); return e;
    }
    static bool Tenant(ClaimsPrincipal p, out Guid id) => Guid.TryParse(p.FindFirstValue("tenant_id"), out id);
    static IResult Error(TemplateOperationException x) => x.Code switch { "NOT_FOUND" => Results.NotFound(new { error = "Not found", code = x.Code, statusCode = 404 }), "TEMPLATE_CODE_EXISTS" or "TEMPLATE_KEY_EXISTS" or "TEMPLATE_DRAFT_EXISTS" or "TEMPLATE_INVALID_STATE" => Results.Conflict(new { error = "Template conflict", code = x.Code, statusCode = 409 }), _ => Results.BadRequest(new { error = "Template validation failed", code = x.Code, statusCode = 400, names = x.Names }) };
    static async Task<IResult> Create(CreateTemplateRequest r, IValidator<CreateTemplateRequest> v, TemplateHandlers h, ClaimsPrincipal p, HttpContext http, CancellationToken c) { if (!(await v.ValidateAsync(r, c)).IsValid) return Error(new("VALIDATION_FAILED")); if (!Tenant(p, out var t)) return Results.Unauthorized(); try { var legacy = r.TemplateCode is null; if (legacy) Deprecated(http); var x = await h.CreateAsync(t, new(r.TemplateCode ?? r.Key!, r.Scope ?? TemplateScope.Tenant, r.SourceDeviceId, r.Audience ?? TemplateAudience.User, r.Subject!, r.TextBody ?? r.Body, r.HtmlBody, r.Variables!), c); return Results.Created($"/v1/templates/{x.Id}", legacy ? Legacy(x) : x); } catch (TemplateOperationException x) { return Error(x); } }
    static async Task<IResult> List(string? scope, Guid? sourceDeviceId, string? audience, string? status, int? limit, string? cursor, TemplateHandlers h, ClaimsPrincipal p, CancellationToken c) { if (!Tenant(p, out var t)) return Results.Unauthorized(); var take = limit ?? 50; if (take is < 1 or > 100 || scope is not null and not ("tenant" or "source") || audience is not null and not ("user" or "system") || status is not null and not ("draft" or "active" or "retired")) return Error(new("VALIDATION_FAILED")); try { var x = await h.ListAsync(t, scope, sourceDeviceId, audience, status, take, cursor, c); return Results.Ok(new { items = x.Items, nextCursor = x.NextCursor }); } catch (TemplateOperationException x) { return Error(x); } }
    static async Task<IResult> Get(string identifier, TemplateHandlers h, ClaimsPrincipal p, HttpContext http, CancellationToken c) { if (!Tenant(p, out var t)) return Results.Unauthorized(); try { if (Guid.TryParse(identifier, out var id)) return Results.Ok(await h.GetAsync(t, id, c)); Deprecated(http); return Results.Ok(Legacy(await h.GetLegacyAsync(t, identifier, c))); } catch (TemplateOperationException x) { return Error(x); } }
    static async Task<IResult> Patch(string identifier, JsonElement body, TemplateHandlers h, ClaimsPrincipal p, HttpContext http, CancellationToken c) { if (!Tenant(p, out var t)) return Results.Unauthorized(); if (!Guid.TryParse(identifier, out var id)) { Deprecated(http); return await PatchLegacy(t, identifier, body, h, c); } if (body.ValueKind != JsonValueKind.Object || !body.EnumerateObject().Any()) return Error(new("VALIDATION_FAILED")); var allowed = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "subject", "textBody", "htmlBody", "variables" }; if (body.EnumerateObject().Any(x => !allowed.Contains(x.Name))) return Error(new("VALIDATION_FAILED")); try { string? subject = GetString(body, "subject"); var hasText = Has(body, "textBody"); var hasHtml = Has(body, "htmlBody"); var variables = GetStrings(body, "variables"); return Results.Ok(await h.UpdateAsync(t, id, new(subject, GetString(body, "textBody"), hasText, GetString(body, "htmlBody"), hasHtml, variables), c)); } catch (TemplateOperationException x) { return Error(x); } catch { return Error(new("VALIDATION_FAILED")); } }
    static async Task<IResult> PatchLegacy(Guid t, string key, JsonElement body, TemplateHandlers h, CancellationToken c) { try { var current = await h.GetLegacyAsync(t, key, c); var status = GetString(body, "status"); if (status == "active") return Results.Ok(Legacy(await h.PublishAsync(t, current.Id, c))); if (status == "retired") return Results.Ok(Legacy(await h.RetireAsync(t, current.Id, c))); return Results.Ok(Legacy(await h.UpdateAsync(t, current.Id, new(GetString(body, "subject"), GetString(body, "body"), Has(body, "body"), null, false, GetStrings(body, "variables")), c))); } catch (TemplateOperationException x) { return Error(x); } catch { return Error(new("VALIDATION_FAILED")); } }
    static async Task<IResult> Clone(Guid id, TemplateHandlers h, ClaimsPrincipal p, CancellationToken c) => await Act(id, h, p, c, h.CloneAsync, created: true);
    static async Task<IResult> Publish(Guid id, TemplateHandlers h, ClaimsPrincipal p, CancellationToken c) => await Act(id, h, p, c, h.PublishAsync);
    static async Task<IResult> Retire(Guid id, TemplateHandlers h, ClaimsPrincipal p, CancellationToken c) => await Act(id, h, p, c, h.RetireAsync);
    static async Task<IResult> Act(Guid id, TemplateHandlers h, ClaimsPrincipal p, CancellationToken c, Func<Guid, Guid, CancellationToken, Task<TemplateItem>> action, bool created = false) { if (!Tenant(p, out var t)) return Results.Unauthorized(); try { var x = await action(t, id, c); return created ? Results.Created($"/v1/templates/{x.Id}", x) : Results.Ok(x); } catch (TemplateOperationException x) { return Error(x); } }
    static object Legacy(TemplateItem x) => new { x.Id, Key = x.TemplateCode, x.Subject, Body = x.TextBody ?? "", x.Variables, x.Status, x.CreatedAt, x.UpdatedAt };
    static bool Has(JsonElement e, string name) => e.TryGetProperty(name, out _);
    static string? GetString(JsonElement e, string name) => e.TryGetProperty(name, out var x) ? x.ValueKind == JsonValueKind.Null ? null : x.GetString() : null;
    static string[]? GetStrings(JsonElement e, string name) => e.TryGetProperty(name, out var x) ? x.Deserialize<string[]>() : null;
    static void Deprecated(HttpContext http) => http.Response.Headers.Append("Deprecation", "true");
}
